# Generated by Django 3.2.16 on 2024-11-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
