# Generated by Django 3.2.16 on 2024-11-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',), 'verbose_name': 'коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
